
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 27 19:06:58 EDT 2019
//----------------------------------------------------


/** CUP v0.10k generated parser.
  * @version Wed Mar 27 19:06:58 EDT 2019
  */
public class SeaParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public SeaParser() {super();}

  /** Constructor which sets the default scanner. */
  public SeaParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\057\000\002\003\004\000\002\002\004\000\002\006" +
    "\003\000\002\006\003\000\002\006\003\000\002\006\003" +
    "\000\002\006\003\000\002\006\003\000\002\006\003\000" +
    "\002\006\003\000\002\006\003\000\002\006\003\000\002" +
    "\007\003\000\002\007\003\000\002\004\004\000\002\004" +
    "\002\000\002\005\004\000\002\005\002\000\002\010\012" +
    "\000\002\010\010\000\002\011\004\000\002\011\002\000" +
    "\002\012\005\000\002\012\002\000\002\013\005\000\002" +
    "\014\006\000\002\016\004\000\002\016\002\000\002\015" +
    "\007\000\002\015\003\000\002\015\003\000\002\015\003" +
    "\000\002\015\003\000\002\021\006\000\002\017\004\000" +
    "\002\017\004\000\002\017\007\000\002\020\010\000\002" +
    "\020\006\000\002\022\003\000\002\022\004\000\002\022" +
    "\003\000\002\023\005\000\002\023\007\000\002\023\007" +
    "\000\002\024\005\000\002\024\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\127\000\010\002\ufff2\023\ufff2\060\006\001\002\000" +
    "\004\002\131\001\002\000\006\002\ufff0\023\012\001\002" +
    "\000\010\002\ufff2\023\ufff2\060\006\001\002\000\006\002" +
    "\ufff3\023\ufff3\001\002\000\006\002\ufff0\023\012\001\002" +
    "\000\004\002\001\001\002\000\004\004\013\001\002\000" +
    "\004\035\014\001\002\000\006\004\015\036\uffec\001\002" +
    "\000\004\045\126\001\002\000\004\036\024\001\002\000" +
    "\006\036\uffea\041\020\001\002\000\004\004\015\001\002" +
    "\000\004\036\uffed\001\002\000\006\036\uffea\041\020\001" +
    "\002\000\004\036\uffeb\001\002\000\006\033\025\045\026" +
    "\001\002\000\014\004\053\026\051\027\055\031\052\033" +
    "\025\001\002\000\030\004\037\007\042\010\043\011\035" +
    "\012\032\013\034\014\036\015\030\016\044\017\031\020" +
    "\033\001\002\000\006\002\uffee\023\uffee\001\002\000\020" +
    "\033\ufff9\036\ufff9\037\ufff9\040\ufff9\041\ufff9\052\ufff9\053" +
    "\ufff9\001\002\000\020\033\ufff7\036\ufff7\037\ufff7\040\ufff7" +
    "\041\ufff7\052\ufff7\053\ufff7\001\002\000\020\033\ufffc\036" +
    "\ufffc\037\ufffc\040\ufffc\041\ufffc\052\ufffc\053\ufffc\001\002" +
    "\000\020\033\ufff6\036\ufff6\037\ufff6\040\ufff6\041\ufff6\052" +
    "\ufff6\053\ufff6\001\002\000\020\033\ufffb\036\ufffb\037\ufffb" +
    "\040\ufffb\041\ufffb\052\ufffb\053\ufffb\001\002\000\020\033" +
    "\ufffd\036\ufffd\037\ufffd\040\ufffd\041\ufffd\052\ufffd\053\ufffd" +
    "\001\002\000\020\033\ufffa\036\ufffa\037\ufffa\040\ufffa\041" +
    "\ufffa\052\ufffa\053\ufffa\001\002\000\014\033\ufff5\036\ufff5" +
    "\037\ufff5\040\ufff5\041\ufff5\001\002\000\014\033\ufff4\036" +
    "\ufff4\037\ufff4\040\ufff4\041\ufff4\001\002\000\004\033\025" +
    "\001\002\000\020\033\uffff\036\uffff\037\uffff\040\uffff\041" +
    "\uffff\052\uffff\053\uffff\001\002\000\020\033\ufffe\036\ufffe" +
    "\037\ufffe\040\ufffe\041\ufffe\052\ufffe\053\ufffe\001\002\000" +
    "\020\033\ufff8\036\ufff8\037\ufff8\040\ufff8\041\ufff8\052\ufff8" +
    "\053\ufff8\001\002\000\006\002\uffef\023\uffef\001\002\000" +
    "\016\004\uffe3\026\uffe3\027\uffe3\031\uffe3\033\uffe3\034\uffe3" +
    "\001\002\000\016\004\uffe2\026\uffe2\027\uffe2\031\uffe2\033" +
    "\uffe2\034\uffe2\001\002\000\016\004\uffe4\026\uffe4\027\uffe4" +
    "\031\uffe4\033\uffe4\034\uffe4\001\002\000\004\004\121\001" +
    "\002\000\006\004\064\006\063\001\002\000\006\035\100" +
    "\037\101\001\002\000\016\004\053\026\051\027\055\031" +
    "\052\033\025\034\uffe6\001\002\000\004\004\057\001\002" +
    "\000\016\004\uffe1\026\uffe1\027\uffe1\031\uffe1\033\uffe1\034" +
    "\uffe1\001\002\000\006\037\062\045\061\001\002\000\016" +
    "\004\uffdf\026\uffdf\027\uffdf\031\uffdf\033\uffdf\034\uffdf\001" +
    "\002\000\030\004\037\007\042\010\043\011\035\012\032" +
    "\013\034\014\036\015\030\016\044\017\031\020\033\001" +
    "\002\000\006\004\064\006\063\001\002\000\036\007\042" +
    "\010\043\011\035\012\032\013\034\014\036\015\030\016" +
    "\044\017\031\020\033\033\uffda\040\uffda\052\uffda\053\uffda" +
    "\001\002\000\012\033\uffd8\040\uffd8\052\uffd8\053\uffd8\001" +
    "\002\000\004\040\066\001\002\000\016\004\uffdb\026\uffdb" +
    "\027\uffdb\031\uffdb\033\uffdb\034\uffdb\001\002\000\012\033" +
    "\uffd9\040\uffd9\052\uffd9\053\uffd9\001\002\000\004\037\071" +
    "\001\002\000\006\004\064\006\063\001\002\000\004\040" +
    "\073\001\002\000\016\004\uffdc\026\uffdc\027\uffdc\031\uffdc" +
    "\033\uffdc\034\uffdc\001\002\000\004\034\077\001\002\000" +
    "\016\004\053\026\051\027\055\031\052\033\025\034\uffe6" +
    "\001\002\000\004\034\uffe7\001\002\000\024\002\uffe8\004" +
    "\uffe8\023\uffe8\026\uffe8\027\uffe8\031\uffe8\032\uffe8\033\uffe8" +
    "\034\uffe8\001\002\000\004\005\104\001\002\000\006\004" +
    "\064\006\063\001\002\000\004\040\103\001\002\000\016" +
    "\004\uffe0\026\uffe0\027\uffe0\031\uffe0\033\uffe0\034\uffe0\001" +
    "\002\000\004\036\105\001\002\000\004\040\106\001\002" +
    "\000\016\004\uffe5\026\uffe5\027\uffe5\031\uffe5\033\uffe5\034" +
    "\uffe5\001\002\000\004\033\025\001\002\000\006\052\111" +
    "\053\112\001\002\000\006\004\064\006\063\001\002\000" +
    "\006\004\064\006\063\001\002\000\004\033\uffd3\001\002" +
    "\000\004\033\uffd4\001\002\000\020\004\uffd7\026\uffd7\027" +
    "\uffd7\031\uffd7\032\116\033\uffd7\034\uffd7\001\002\000\006" +
    "\031\052\033\025\001\002\000\016\004\uffd5\026\uffd5\027" +
    "\uffd5\031\uffd5\033\uffd5\034\uffd5\001\002\000\016\004\uffd6" +
    "\026\uffd6\027\uffd6\031\uffd6\033\uffd6\034\uffd6\001\002\000" +
    "\006\037\062\045\123\001\002\000\016\004\uffde\026\uffde" +
    "\027\uffde\031\uffde\033\uffde\034\uffde\001\002\000\030\004" +
    "\037\007\042\010\043\011\035\012\032\013\034\014\036" +
    "\015\030\016\044\017\031\020\033\001\002\000\006\037" +
    "\071\040\125\001\002\000\016\004\uffdd\026\uffdd\027\uffdd" +
    "\031\uffdd\033\uffdd\034\uffdd\001\002\000\030\004\037\007" +
    "\042\010\043\011\035\012\032\013\034\014\036\015\030" +
    "\016\044\017\031\020\033\001\002\000\006\036\uffe9\041" +
    "\uffe9\001\002\000\004\002\ufff1\001\002\000\004\002\000" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\127\000\006\003\003\004\004\001\001\000\002\001" +
    "\001\000\006\005\010\010\007\001\001\000\004\004\006" +
    "\001\001\000\002\001\001\000\006\005\127\010\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\011\015\013\016\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\012\020\001\001\000\004\013\021" +
    "\001\001\000\002\001\001\000\004\012\022\001\001\000" +
    "\002\001\001\000\004\014\026\001\001\000\014\014\047" +
    "\015\053\017\055\021\046\023\045\001\001\000\006\006" +
    "\037\007\040\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\014\044\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\020\121\001\001\000\006\022\107\024\106" +
    "\001\001\000\002\001\001\000\016\014\047\015\074\016" +
    "\073\017\055\021\046\023\045\001\001\000\004\020\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\006\037\007\067\001\001\000\004\022\064" +
    "\001\001\000\004\006\066\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\022\071\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\014\047\015\074" +
    "\016\075\017\055\021\046\023\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\022\101" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\114" +
    "\001\001\000\002\001\001\000\004\022\113\001\001\000" +
    "\004\022\112\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\014\117\023\116\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\037\007\123\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\006\037\007\126\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SeaParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SeaParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SeaParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$SeaParser$actions {
  private final SeaParser parser;

  /** Constructor */
  CUP$SeaParser$actions(SeaParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$SeaParser$do_action(
    int                        CUP$SeaParser$act_num,
    java_cup.runtime.lr_parser CUP$SeaParser$parser,
    java.util.Stack            CUP$SeaParser$stack,
    int                        CUP$SeaParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SeaParser$result;

      /* select the action based on the action number */
      switch (CUP$SeaParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // bool_expr ::= expression NEQUALITY expression 
            {
              String RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = e + " != " + x;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(18/*bool_expr*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // bool_expr ::= expression EQUALITY expression 
            {
              String RESULT = null;
		int eleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = e + " == " + x;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(18/*bool_expr*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // if_stmt ::= IF bool_expr block ELSE if_stmt 
            {
              String RESULT = null;
		int bleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = "if (" + b + ") " + l + "else " + i; 
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(17/*if_stmt*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // if_stmt ::= IF bool_expr block ELSE block 
            {
              String RESULT = null;
		int bleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String o = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = "if (" + b + ") " + l + "else " + o; 
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(17/*if_stmt*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // if_stmt ::= IF bool_expr block 
            {
              String RESULT = null;
		int bleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int lleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String l = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = "if (" + b + ") " + l;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(17/*if_stmt*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expression ::= ID 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = i + "";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(16/*expression*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expression ::= NUM num_type 
            {
              String RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = n + "";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(16/*expression*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expression ::= NUM 
            {
              String RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = n + "";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(16/*expression*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // _var_decl ::= ID ASSIGN expression SEMICOLON 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		
				// TODO: this is going to be used in type inference later
				RESULT = i + " = " + e + ";";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(14/*_var_decl*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // _var_decl ::= ID COLON type ASSIGN expression SEMICOLON 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-5)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-5)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-5)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		
				RESULT = t + " " + i + " = " + e + ";";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(14/*_var_decl*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // var_decl ::= MUT ID COLON type SEMICOLON 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		
				RESULT = t + " " + i + ";";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(13/*var_decl*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // var_decl ::= MUT _var_decl 
            {
              String RESULT = null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = v + "";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(13/*var_decl*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // var_decl ::= LET _var_decl 
            {
              String RESULT = null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = "const " + v;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(13/*var_decl*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // assign_stmt ::= ID ASSIGN expression SEMICOLON 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		
				RESULT = i + " = " + e + ";";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(15/*assign_stmt*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // statement ::= var_decl 
            {
              String RESULT = null;
		int vleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = v + "";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(11/*statement*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // statement ::= assign_stmt 
            {
              String RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = a + "";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(11/*statement*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // statement ::= if_stmt 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = i + "";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(11/*statement*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // statement ::= block 
            {
              String RESULT = null;
		int bleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = b + "";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(11/*statement*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // statement ::= ID LPAREN QSTRING RPAREN SEMICOLON 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).value;
		int qleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left;
		int qright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).right;
		Object q = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).value;
		
				RESULT = i + "(" + q + ");";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(11/*statement*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // _statement ::= 
            {
              String RESULT = null;
		 RESULT = ""; 
              CUP$SeaParser$result = new java_cup.runtime.Symbol(12/*_statement*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // _statement ::= statement _statement 
            {
              String RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = s + "\n" + t;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(12/*_statement*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // block ::= BEGIN statement _statement END 
            {
              String RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		
				RESULT = "{\n" + s + "\n" + t + "}\n";
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(10/*block*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-3)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // decl_param ::= ID COLON type 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = t + i;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(9/*decl_param*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // _decl_params ::= 
            {
              String RESULT = null;
		 RESULT = ""; 
              CUP$SeaParser$result = new java_cup.runtime.Symbol(8/*_decl_params*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // _decl_params ::= COMMA decl_param _decl_params 
            {
              String RESULT = null;
		int dleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = "," + d + p;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(8/*_decl_params*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // decl_params ::= 
            {
              String RESULT = null;
		 RESULT = ""; 
              CUP$SeaParser$result = new java_cup.runtime.Symbol(7/*decl_params*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // decl_params ::= decl_param _decl_params 
            {
              String RESULT = null;
		int dleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String p = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = d + p;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(7/*decl_params*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // function ::= FN ID LPAREN decl_params RPAREN block 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = "void " + i + "(" + d + ") " + b;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(6/*function*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-5)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // function ::= FN ID LPAREN decl_params RPAREN COLON type block 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-6)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-6)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-6)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-4)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = t + " " + i + "(" + d + ") " + b;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(6/*function*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-7)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // definitions ::= 
            {
              String RESULT = null;
		 RESULT = ""; 
              CUP$SeaParser$result = new java_cup.runtime.Symbol(3/*definitions*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // definitions ::= function definitions 
            {
              String RESULT = null;
		int fleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = f + d;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(3/*definitions*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // includes ::= 
            {
              String RESULT = null;
		 RESULT = ""; 
              CUP$SeaParser$result = new java_cup.runtime.Symbol(2/*includes*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // includes ::= INCLUDE includes 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = "#include" + i + n;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(2/*includes*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // type ::= num_type 
            {
              String RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		 RESULT = n + ""; 
              CUP$SeaParser$result = new java_cup.runtime.Symbol(5/*type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // type ::= ID 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		Object i = (Object)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
			RESULT = i + ""; 
              CUP$SeaParser$result = new java_cup.runtime.Symbol(5/*type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // num_type ::= F32 
            {
              String RESULT = null;
			RESULT = "float";	
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // num_type ::= F64 
            {
              String RESULT = null;
			RESULT = "double";	
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // num_type ::= U8 
            {
              String RESULT = null;
			RESULT = "uint8_t";	
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // num_type ::= U16 
            {
              String RESULT = null;
			RESULT = "uint16_t";
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // num_type ::= U32 
            {
              String RESULT = null;
			RESULT = "uint32_t";
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // num_type ::= U64 
            {
              String RESULT = null;
			RESULT = "uint64_t";
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // num_type ::= I8 
            {
              String RESULT = null;
			RESULT = "int8_t";	
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // num_type ::= I16 
            {
              String RESULT = null;
			RESULT = "int16_t";	
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // num_type ::= I32 
            {
              String RESULT = null;
			RESULT = "int32_t";	
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // num_type ::= I64 
            {
              String RESULT = null;
			RESULT = "int64_t";	
              CUP$SeaParser$result = new java_cup.runtime.Symbol(4/*num_type*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		RESULT = start_val;
              CUP$SeaParser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$SeaParser$parser.done_parsing();
          return CUP$SeaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= includes definitions 
            {
              String RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right;
		String d = (String)((java_cup.runtime.Symbol) CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).value;
		
				RESULT = i + d;
			
              CUP$SeaParser$result = new java_cup.runtime.Symbol(1/*program*/, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-1)).left, ((java_cup.runtime.Symbol)CUP$SeaParser$stack.elementAt(CUP$SeaParser$top-0)).right, RESULT);
            }
          return CUP$SeaParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

