
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Mar 23 13:38:49 EDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class SeaSymbol {
  /* terminals */
  public static final int SHR = 45;
  public static final int DIVIDE = 40;
  public static final int QSTRING = 3;
  public static final int EQUALITY = 41;
  public static final int SHL = 44;
  public static final int LPAREN = 28;
  public static final int MINUS = 39;
  public static final int USIZE = 15;
  public static final int STAR = 35;
  public static final int STATIC = 20;
  public static final int RPAREN = 29;
  public static final int NEQUALITY = 42;
  public static final int NOT = 43;
  public static final int SEMICOLON = 31;
  public static final int FN = 18;
  public static final int COMMA = 32;
  public static final int I32 = 6;
  public static final int I64 = 5;
  public static final int COMPLEMENT = 46;
  public static final int BEGIN = 26;
  public static final int NUM = 4;
  public static final int PLUS = 38;
  public static final int ASSIGN = 30;
  public static final int IF = 24;
  public static final int MUT = 21;
  public static final int DOT = 33;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int error = 1;
  public static final int INCLUDE = 47;
  public static final int I8 = 8;
  public static final int U16 = 11;
  public static final int WIDE_CHAR = 17;
  public static final int U8 = 12;
  public static final int GETPTR = 34;
  public static final int COLON = 36;
  public static final int ELSE = 25;
  public static final int F64 = 13;
  public static final int F32 = 14;
  public static final int LET = 22;
  public static final int SSIZE = 16;
  public static final int END = 27;
  public static final int STRUCT = 19;
  public static final int DEREF = 37;
  public static final int I16 = 7;
  public static final int U32 = 10;
  public static final int U64 = 9;
}

