
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Mar 27 19:06:58 EDT 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class SeaSymbol {
  /* terminals */
  public static final int SHR = 44;
  public static final int DIVIDE = 39;
  public static final int QSTRING = 3;
  public static final int EQUALITY = 40;
  public static final int SHL = 43;
  public static final int LPAREN = 27;
  public static final int MINUS = 38;
  public static final int USIZE = 15;
  public static final int STAR = 34;
  public static final int STATIC = 19;
  public static final int RPAREN = 28;
  public static final int NEQUALITY = 41;
  public static final int NOT = 42;
  public static final int SEMICOLON = 30;
  public static final int FN = 17;
  public static final int COMMA = 31;
  public static final int I32 = 6;
  public static final int I64 = 5;
  public static final int COMPLEMENT = 45;
  public static final int BEGIN = 25;
  public static final int NUM = 4;
  public static final int PLUS = 37;
  public static final int ASSIGN = 29;
  public static final int IF = 23;
  public static final int MUT = 20;
  public static final int DOT = 32;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int error = 1;
  public static final int INCLUDE = 46;
  public static final int I8 = 8;
  public static final int U16 = 11;
  public static final int WIDE_CHAR = 16;
  public static final int U8 = 12;
  public static final int GETPTR = 33;
  public static final int COLON = 35;
  public static final int ELSE = 24;
  public static final int F64 = 13;
  public static final int F32 = 14;
  public static final int LET = 21;
  public static final int END = 26;
  public static final int STRUCT = 18;
  public static final int DEREF = 36;
  public static final int I16 = 7;
  public static final int U32 = 10;
  public static final int U64 = 9;
}

